### ISSUE TITLE
Bot works fine in --test on terminal, but doesnt want to deploy to discord

### ISSUE THREAD

**Issue by Awsomedude0361** [johnnymcmike/Gravital#9]
I keep getting this error when I try and run 'main.py --token "insert token"'

Traceback (most recent call last):
  File "C:\Users\Akshay\Downloads\Gravital-master\main.py", line 57, in <module>
    main()
  File "C:\Users\Akshay\Downloads\Gravital-master\main.py", line 48, in main
    client = ChatBot(args.maxlines)
  File "C:\Users\Akshay\Downloads\Gravital-master\Bot\bot.py", line 18, in __init__
    super().__init__()
TypeError: Client.__init__() missing 1 required keyword-only argument: 'intents'

But it works perfectly fine when I do 'main.py --test' So im sure my trained model works.

**Comment by Awsomedude0361** [comment]
Hahaha, nvm I fixed it after a bit of scouring through the code

The discord.py was 1.7.3 because I installed it through requirements.txt but the code was coded in discord.py 2.0.0

**Comment by johnnymcmike** [comment]
Will update requirements.txt, thanks for letting me know!
